listen              1935;
max_connections     1000;
daemon              off;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

vhost __defaultVhost__ {
    hls {
        enabled     on;
        hls_fragment    3;
        hls_window      60;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    http_hooks {
        enabled         on;
        # dev: fastify 跑在 host，用 host.docker.internal 連回去
        on_play         http://host.docker.internal:9090/api/v1/srs/on_play;
        on_publish      http://host.docker.internal:9090/api/v1/srs/on_publish;
        on_stop         http://host.docker.internal:9090/api/v1/srs/on_stop;
    }
}
